[package]
name = "coco-reasoner"
version = "0.1.0"
authors = ["Riccardo De Benedictis"]
edition = "2024"
description = "Combined deduction and abduCtion (CoCo) reasoner is a dual-process inspired cognitive architecture built in Rust"
readme = "README.md"
repository = "https://github.com/ratioSolver/COCO"
license-file = "LICENSE.txt"

[lib]
name = "coco"

[dependencies]
axum = { version = "0.8.8", features = ["ws"] }
tower-http = { version = "0.5", features = ["fs"] }
tokio = { version = "1.49", features = ["full"] }
serde = "1.0.228"
mongodb = { version = "3.5.0" }
futures = "0.3.31"
async-trait = "0.1.89"
chrono = { version = "0.4.43", features = ["serde"] }
