(defrule anxiety
    (User_baseline_fall (item_id ?user) (baseline_fall ?baseline_fall))
    (User_baseline_freezing (item_id ?user) (baseline_freezing ?baseline_freezing))
    (User_baseline_heart_rate (item_id ?user) (baseline_heart_rate ?baseline_heart_rate))
    (User_state_anxiety_presence (item_id ?user) (state_anxiety_presence ?state_anxiety_presence))
    (User_stress (item_id ?user) (stress ?stress))
    (User_psychiatric_disorders (item_id ?user) (psychiatric_disorders ?psychiatric_disorders))

    (User_parkinson (item_id ?user) (parkinson ?parkinson))
    (User_older_adults (item_id ?user) (older_adults ?older_adults))
    (User_psychiatric_patients (item_id ?user) (psychiatric_patients ?psychiatric_patients))
    (User_multiple_sclerosis (item_id ?user) (multiple_sclerosis ?multiple_sclerosis))
    (User_young_pci_autism (item_id ?user) (young_pci_autism ?young_pci_autism))

    (User_has_FREEZING (item_id ?user) (FREEZING ?FREEZING))
    (User_has_crowding (item_id ?user) (crowding ?crowding))
    (User_has_sleep_duration_quality (item_id ?user) (sleep_duration_quality ?sleep_duration_quality))
    (User_has_recent_freezing_episodes (item_id ?user) (recent_freezing_episodes ?recent_freezing_episodes))
    (User_has_heart_rate (item_id ?user) (heart_rate ?heart_rate))
    (User_has_heart_rate_differential (item_id ?user) (heart_rate_differential ?heart_rate_differential))
    (User_has_public_events_frequency (item_id ?user) (public_events_frequency ?public_events_frequency))
    (User_has_respiratory_rate (item_id ?user) (respiratory_rate ?respiratory_rate))
    (User_has_galvanic_skin_response (item_id ?user) (galvanic_skin_response ?galvanic_skin_response))
    (User_has_noise_pollution (item_id ?user) (noise_pollution ?noise_pollution))
    (User_has_user_reported_noise_pollution (item_id ?user) (user_reported_noise_pollution ?user_reported_noise_pollution))
    (User_has_traffic_levels (item_id ?user) (traffic_levels ?traffic_levels))
    (User_has_lack_of_ventilation (item_id ?user) (lack_of_ventilation ?lack_of_ventilation))
    (User_has_safety_perception (item_id ?user) (safety_perception ?safety_perception))
    (User_has_rough_path (item_id ?user) (rough_path ?rough_path))
    (User_has_public_events_presence (item_id ?user) (public_events_presence ?public_events_presence))
    (User_has_high_blood_pressure (item_id ?user) (high_blood_pressure ?high_blood_pressure))
    (User_has_social_pressure (item_id ?user) (social_pressure ?social_pressure))
    (User_has_self_perception (item_id ?user) (self_perception ?self_perception))
    (User_has_sweating (item_id ?user) (sweating ?sweating))
    (User_has_body_temperature (item_id ?user) (body_temperature ?body_temperature))
    (User_has_excessive_urbanization (item_id ?user) (excessive_urbanization ?excessive_urbanization))
=>
    (printout t "Updating anxiety!" crlf)
    (bind ?anxiety 0)
    (bind ?anxiety_relevant (create$))

    (if (and (or ?parkinson ?older_adults ?psychiatric_patients ?multiple_sclerosis ?young_pci_autism) (>= ?crowding 2)) then (bind ?anxiety (+ ?anxiety 1)))
    (if (and ?parkinson (>= ?baseline_fall 6)) then (bind ?anxiety (+ ?anxiety 1)))
    (if (and (or ?parkinson ?psychiatric_patients ?multiple_sclerosis ?young_pci_autism) (< ?sleep_duration_quality 6)) then (bind ?anxiety (+ ?anxiety 1)))
    (if (and ?parkinson ?FREEZING) then (bind ?anxiety (+ ?anxiety 1)))
    (if (and ?psychiatric_patients ?public_events_frequency) then (bind ?anxiety (+ ?anxiety 1)))
    (if (and (or ?older_adults ?parkinson ?psychiatric_patients ?multiple_sclerosis ?young_pci_autism) (> ?noise_pollution 45)) then (bind ?anxiety (+ ?anxiety 1)))
    (if (and (or ?older_adults ?parkinson ?psychiatric_patients ?multiple_sclerosis ?young_pci_autism) (> ?user_reported_noise_pollution 45)) then (bind ?anxiety (+ ?anxiety 1)))
    (if (and ?psychiatric_patients (> ?traffic_levels 50)) then (bind ?anxiety (+ ?anxiety 1)))
    (if (and ?psychiatric_patients (> ?lack_of_ventilation 1000)) then (bind ?anxiety (+ ?anxiety 1)))
    (if (and ?older_adults ?safety_perception) then (bind ?anxiety (+ ?anxiety 1)))
    (if (and ?older_adults ?rough_path) then (bind ?anxiety (+ ?anxiety 1)))
    (if (and ?older_adults ?public_events_presence) then (bind ?anxiety (+ ?anxiety 1)))
    (if (and (or ?psychiatric_patients ?parkinson ?older_adults) ?state_anxiety_presence) then (bind ?anxiety (+ ?anxiety 1)))
    (if (and ?multiple_sclerosis ?social_pressure) then (bind ?anxiety (+ ?anxiety 1)))
    (if (and ?older_adults (> ?stress 27)) then (bind ?anxiety (+ ?anxiety 1)))
    (if (and ?older_adults ?excessive_urbanization) then (bind ?anxiety (+ ?anxiety 1)))
    (if (and ?psychiatric_patients ?psychiatric_disorders) then (bind ?anxiety (+ ?anxiety 1)))

    (if (and ?parkinson ?baseline_freezing) then (bind ?anxiety_relevant (insert$ ?anxiety_relevant 1 baseline_freezing)))
    (if (and ?parkinson (>= ?recent_freezing_episodes 3)) then (bind ?anxiety_relevant (insert$ ?anxiety_relevant 1 recent_freezing_episodes)))
    (if (and (or ?parkinson ?psychiatric_patients ?multiple_sclerosis ?young_pci_autism) (>= ?heart_rate 100)) then (bind ?anxiety_relevant (insert$ ?anxiety_relevant 1 heart_rate)))
    (if (and (or ?psychiatric_patients ?young_pci_autism) (>= ?baseline_heart_rate 100)) then (bind ?anxiety_relevant (insert$ ?anxiety_relevant 1 baseline_heart_rate)))
    (if (and (or ?psychiatric_patients ?young_pci_autism ?parkinson ?multiple_sclerosis) (>= ?heart_rate_differential 50)) then (bind ?anxiety_relevant (insert$ ?anxiety_relevant 1 heart_rate_differential)))
    (if (and (or ?parkinson ?psychiatric_patients ?older_adults ?multiple_sclerosis ?young_pci_autism) (>= ?respiratory_rate 30)) then (bind ?anxiety_relevant (insert$ ?anxiety_relevant 1 respiratory_rate)))
    (if (and ?psychiatric_patients (>= ?galvanic_skin_response 50)) then (bind ?anxiety_relevant (insert$ ?anxiety_relevant 1 galvanic_skin_response)))
    (if (and ?older_adults (>= ?high_blood_pressure 100)) then (bind ?anxiety_relevant (insert$ ?anxiety_relevant 1 high_blood_pressure)))
    (if (and ?multiple_sclerosis ?self_perception) then (bind ?anxiety_relevant (insert$ ?anxiety_relevant 1 self_perception)))
    (if (and (or ?older_adults ?parkinson) (>= ?sweating 10)) then (bind ?anxiety_relevant (insert$ ?anxiety_relevant 1 sweating)))
    (if (and (or ?psychiatric_patients ?older_adults ?parkinson) (> ?body_temperature 37.3)) then (bind ?anxiety_relevant (insert$ ?anxiety_relevant 1 body_temperature)))

    (printout t "User: " ?user crlf)
    (printout t "Anxiety: " ?anxiety crlf)
    (printout t "Anxiety Relevant Factors: " ?anxiety_relevant crlf)

    (if (and (>= ?anxiety 0) (<= ?anxiety 1)) then (add_data ?user (create$ ANXIETY anxiety_relevant) (create$ low ?anxiety_relevant)))
    (if (and (>= ?anxiety 2) (<= ?anxiety 3)) then (add_data ?user (create$ ANXIETY anxiety_relevant) (create$ medium ?anxiety_relevant)))
    (if (>= ?anxiety 4) then (add_data ?user (create$ ANXIETY anxiety_relevant) (create$ high ?anxiety_relevant)))
)