(defrule excessive_heat
    (User_baseline_heart_rate (item_id ?user) (baseline_heart_rate ?baseline_heart_rate))
    (User_baseline_blood_pressure (item_id ?user) (baseline_blood_pressure ?baseline_blood_pressure))

    (User_parkinson (item_id ?user) (parkinson ?parkinson))
    (User_older_adults (item_id ?user) (older_adults ?older_adults))
    (User_psychiatric_patients (item_id ?user) (psychiatric_patients ?psychiatric_patients))
    (User_multiple_sclerosis (item_id ?user) (multiple_sclerosis ?multiple_sclerosis))
    (User_young_pci_autism (item_id ?user) (young_pci_autism ?young_pci_autism))

    (User_has_crowding (item_id ?user) (crowding ?crowding))
    (User_has_altered_thirst_perception (item_id ?user) (altered_thirst_perception ?altered_thirst_perception))
    (User_has_water_balance (item_id ?user) (water_balance ?water_balance))
    (User_has_sleep_duration_quality (item_id ?user) (sleep_duration_quality ?sleep_duration_quality))
    (User_has_heart_rate (item_id ?user) (heart_rate ?heart_rate))
    (User_has_heart_rate_differential (item_id ?user) (heart_rate_differential ?heart_rate_differential))
    (User_has_galvanic_skin_response (item_id ?user) (galvanic_skin_response ?galvanic_skin_response))
    (User_has_low_blood_pressure (item_id ?user) (low_blood_pressure ?low_blood_pressure))
    (User_has_sweating (item_id ?user) (sweating ?sweating))
    (User_has_ambient_temperature (item_id ?user) (ambient_temperature ?ambient_temperature))
    (User_has_body_temperature (item_id ?user) (body_temperature ?body_temperature))
    (User_has_ambient_humidity (item_id ?user) (ambient_humidity ?ambient_humidity))
    (User_has_excessive_urbanization (item_id ?user) (excessive_urbanization ?excessive_urbanization))
=>
    (bind ?excessive_heat 0)
    (bind ?excessive_heat_relevant (create$))

    (if (and (or ?parkinson ?older_adults ?psychiatric_patients ?multiple_sclerosis ?young_pci_autism) (>= ?crowding 2)) then (bind ?excessive_heat (+ ?excessive_heat 1)))
    (if (and (or ?psychiatric_patients) (>= ?altered_thirst_perception 3)) then (bind ?excessive_heat (+ ?excessive_heat 1)))
    (if (and (or ?parkinson ?psychiatric_patients) (< ?water_balance 1)) then (bind ?excessive_heat (+ ?excessive_heat 1)))
    (if (and (or ?parkinson ?psychiatric_patients ?multiple_sclerosis ?young_pci_autism) (< ?sleep_duration_quality 6)) then (bind ?excessive_heat (+ ?excessive_heat 1)))
    (if (and (or ?parkinson ?psychiatric_patients ?multiple_sclerosis ?young_pci_autism) (> ?ambient_temperature 27)) then (bind ?excessive_heat (+ ?excessive_heat 1)))
    (if (and (or ?psychiatric_patients ?older_adults) (> ?ambient_humidity 60)) then (bind ?excessive_heat (+ ?excessive_heat 1)))
    (if (and ?older_adults ?excessive_urbanization) then (bind ?excessive_heat (+ ?excessive_heat 1)))

    (if (and (or ?parkinson ?psychiatric_patients) (< ?water_balance 1)) then (bind ?excessive_heat_relevant (append$ ?excessive_heat_relevant water_balance)))
    (if (and (or ?parkinson ?psychiatric_patients ?multiple_sclerosis ?young_pci_autism) (>= ?heart_rate 100)) then (bind ?excessive_heat_relevant (append$ ?excessive_heat_relevant heart_rate)))
    (if (and (or ?psychiatric_patients ?young_pci_autism) (>= ?baseline_heart_rate 100)) then (bind ?excessive_heat_relevant (append$ ?excessive_heat_relevant baseline_heart_rate)))
    (if (and (or ?psychiatric_patients ?young_pci_autism ?parkinson ?multiple_sclerosis) (>= ?heart_rate_differential 50)) then (bind ?excessive_heat_relevant (append$ ?excessive_heat_relevant heart_rate_differential)))
    (if (and ?psychiatric_patients (>= ?galvanic_skin_response 50)) then (bind ?excessive_heat_relevant (append$ ?excessive_heat_relevant galvanic_skin_response)))
    (if (and ?parkinson (>= ?baseline_blood_pressure 100)) then (bind ?excessive_heat_relevant (append$ ?excessive_heat_relevant baseline_blood_pressure)))
    (if (and ?parkinson (< ?low_blood_pressure 90)) then (bind ?excessive_heat_relevant (append$ ?excessive_heat_relevant low_blood_pressure)))
    (if (and (or ?older_adults ?parkinson) (>= ?sweating 10)) then (bind ?excessive_heat_relevant (append$ ?excessive_heat_relevant sweating)))
    (if (and (or ?psychiatric_patients ?older_adults ?parkinson) (> ?body_temperature 37.5)) then (bind ?excessive_heat_relevant (append$ ?excessive_heat_relevant body_temperature)))

    (if (and (>= ?excessive_heat 0) (<= ?excessive_heat 1)) then (add_data ?user (create$ EXCESSIVE_HEAT excessive_heat_relevant) (create$ "Low" ?excessive_heat_relevant)))
    (if (and (>= ?excessive_heat 2) (<= ?excessive_heat 3)) then (add_data ?user (create$ EXCESSIVE_HEAT excessive_heat_relevant) (create$ "Medium" ?excessive_heat_relevant)))
    (if (>= ?excessive_heat 4) then (add_data ?user (create$ EXCESSIVE_HEAT excessive_heat_relevant) (create$ "High" ?excessive_heat_relevant)))
)