(defrule physical_fatigue
    (User_baseline_nutrition (item_id ?user) (baseline_nutrition ?baseline_nutrition))
    (User_baseline_heart_rate (item_id ?user) (baseline_heart_rate ?baseline_heart_rate))
    (User_baseline_blood_pressure (item_id ?user) (baseline_blood_pressure ?baseline_blood_pressure))

    (User_parkinson (item_id ?user) (parkinson ?parkinson))
    (User_older_adults (item_id ?user) (older_adults ?older_adults))
    (User_psychiatric_patients (item_id ?user) (psychiatric_patients ?psychiatric_patients))
    (User_multiple_sclerosis (item_id ?user) (multiple_sclerosis ?multiple_sclerosis))
    (User_young_pci_autism (item_id ?user) (young_pci_autism ?young_pci_autism))

    (User_has_ANXIETY (item_id ?user) (ANXIETY ?ANXIETY))
    (User_has_altered_nutrition (item_id ?user) (altered_nutrition ?altered_nutrition))
    (User_has_bar_restaurant (item_id ?user) (bar_restaurant ?bar_restaurant))
    (User_has_architectural_barriers (item_id ?user) (architectural_barriers ?architectural_barriers))
    (User_has_water_balance (item_id ?user) (water_balance ?water_balance))
    (User_has_sleep_duration_quality (item_id ?user) (sleep_duration_quality ?sleep_duration_quality))
    (User_has_water_fountains (item_id ?user) (water_fountains ?water_fountains))
    (User_has_heart_rate (item_id ?user) (heart_rate ?heart_rate))
    (User_has_heart_rate_differential (item_id ?user) (heart_rate_differential ?heart_rate_differential))
    (User_has_respiratory_rate (item_id ?user) (respiratory_rate ?respiratory_rate))
    (User_has_noise_pollution (item_id ?user) (noise_pollution ?noise_pollution))
    (User_has_user_reported_noise_pollution (item_id ?user) (user_reported_noise_pollution ?user_reported_noise_pollution))
    (User_has_air_pollution (item_id ?user) (air_pollution ?air_pollution))
    (User_has_path_slope (item_id ?user) (path_slope ?path_slope))
    (User_has_rough_path (item_id ?user) (rough_path ?rough_path))
    (User_has_low_blood_pressure (item_id ?user) (low_blood_pressure ?low_blood_pressure))
    (User_has_sittings (item_id ?user) (sittings ?sittings))
    (User_has_restroom_availability (item_id ?user) (restroom_availability ?restroom_availability))
    (User_has_ambient_temperature (item_id ?user) (ambient_temperature ?ambient_temperature))
    (User_has_green_spaces (item_id ?user) (green_spaces ?green_spaces))
=>
    (bind ?physical_fatigue 0)
    (bind ?physical_fatigue_relevant (create$))

    (if (and (or ?parkinson ?young_pci_autism) ?altered_nutrition) then (bind ?physical_fatigue (+ ?physical_fatigue 1)))
    (if (and (or ?parkinson ?baseline_nutrition) ?baseline_nutrition) then (bind ?physical_fatigue (+ ?physical_fatigue 1)))
    (if (and ?parkinson ?ANXIETY) then (bind ?physical_fatigue (+ ?physical_fatigue 1)))
    (if (and ?parkinson ?architectural_barriers) then (bind ?physical_fatigue (+ ?physical_fatigue 1)))
    (if (and (or ?parkinson ?psychiatric_patients) (< ?water_balance 1)) then (bind ?physical_fatigue (+ ?physical_fatigue 1)))
    (if (and (or ?parkinson ?psychiatric_patients ?multiple_sclerosis ?young_pci_autism) (< ?sleep_duration_quality 6)) then (bind ?physical_fatigue (+ ?physical_fatigue 1)))
    (if (and (or ?parkinson ?multiple_sclerosis ?young_pci_autism) (>= ?heart_rate 100)) then (bind ?physical_fatigue (+ ?physical_fatigue 1)))
    (if (and (or ?psychiatric_patients ?young_pci_autism) (>= ?baseline_heart_rate 100)) then (bind ?physical_fatigue (+ ?physical_fatigue 1)))
    (if (and (or ?psychiatric_patients ?young_pci_autism ?parkinson ?multiple_sclerosis) (>= ?heart_rate_differential 50)) then (bind ?physical_fatigue (+ ?physical_fatigue 1)))
    (if (and (or ?older_adults ?parkinson ?psychiatric_patients ?multiple_sclerosis ?young_pci_autism) (> ?noise_pollution 45)) then (bind ?physical_fatigue (+ ?physical_fatigue 1)))
    (if (and (or ?older_adults ?parkinson ?psychiatric_patients ?multiple_sclerosis ?young_pci_autism) (> ?user_reported_noise_pollution 45)) then (bind ?physical_fatigue (+ ?physical_fatigue 1)))
    (if (and ?older_adults (> ?air_pollution 5)) then (bind ?physical_fatigue (+ ?physical_fatigue 1)))
    (if (and ?multiple_sclerosis ?path_slope) then (bind ?physical_fatigue (+ ?physical_fatigue 1)))
    (if (and ?older_adults ?rough_path) then (bind ?physical_fatigue (+ ?physical_fatigue 1)))
    (if (and ?parkinson (>= ?baseline_blood_pressure 100)) then (bind ?physical_fatigue (+ ?physical_fatigue 1)))
    (if (and ?parkinson (< ?low_blood_pressure 90)) then (bind ?physical_fatigue (+ ?physical_fatigue 1)))
    (if (and (or ?parkinson ?psychiatric_patients ?multiple_sclerosis ?young_pci_autism) (> ?ambient_temperature 27)) then (bind ?physical_fatigue (+ ?physical_fatigue 1)))

    (if (and ?psychiatric_patients ?bar_restaurant) then (bind ?physical_fatigue_relevant (insert$ ?physical_fatigue_relevant 1 bar_restaurant)))
    (if (and ?psychiatric_patients ?water_fountains) then (bind ?physical_fatigue_relevant (insert$ ?physical_fatigue_relevant 1 water_fountains)))
    (if (and (or ?parkinson ?psychiatric_patients ?multiple_sclerosis ?young_pci_autism) (>= ?heart_rate 100)) then (bind ?physical_fatigue_relevant (insert$ ?physical_fatigue_relevant 1 heart_rate)))
    (if (and (or ?psychiatric_patients ?young_pci_autism) (>= ?baseline_heart_rate 100)) then (bind ?physical_fatigue_relevant (insert$ ?physical_fatigue_relevant 1 baseline_heart_rate)))
    (if (and (or ?parkinson ?psychiatric_patients ?older_adults ?multiple_sclerosis ?young_pci_autism) (>= ?respiratory_rate 30)) then (bind ?physical_fatigue_relevant (insert$ ?physical_fatigue_relevant 1 respiratory_rate)))
    (if (and ?psychiatric_patients ?sittings) then (bind ?physical_fatigue_relevant (insert$ ?physical_fatigue_relevant 1 sittings)))
    (if (and ?psychiatric_patients ?restroom_availability) then (bind ?physical_fatigue_relevant (insert$ ?physical_fatigue_relevant 1 restroom_availability)))
    (if (and ?psychiatric_patients ?green_spaces) then (bind ?physical_fatigue_relevant (insert$ ?physical_fatigue_relevant 1 green_spaces)))

    (if (and (>= ?physical_fatigue 0) (<= ?physical_fatigue 1)) then (add_data ?user (create$ PHYSICAL_FATIGUE physical_fatigue_relevant) (create$ "Low" ?physical_fatigue_relevant)))
    (if (and (>= ?physical_fatigue 2) (<= ?physical_fatigue 3)) then (add_data ?user (create$ PHYSICAL_FATIGUE physical_fatigue_relevant) (create$ "Medium" ?physical_fatigue_relevant)))
    (if (>= ?physical_fatigue 4) then (add_data ?user (create$ PHYSICAL_FATIGUE physical_fatigue_relevant) (create$ "High" ?physical_fatigue_relevant)))
)