plugins {
    id 'com.android.library'
}

android {
    namespace = 'it.cnr.coco'
    compileSdk = 34

    defaultConfig {
        minSdk = 26
        targetSdk = 34
    }

    buildTypes {
        release {
            minifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.firebase:firebase-messaging:24.0.0'
    implementation 'com.squareup.okhttp3:okhttp:5.1.0'
    implementation 'com.google.code.gson:gson:2.13.1'
}
